[project]
name = "themus-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "confluent-kafka>=2.3.0",
    "fastapi[standard]>=0.117.1",
    "google-cloud-storage>=3.4.0",
    "greenlet>=3.2.4",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "python-dotenv>=1.1.1",
    "ruff>=0.13.1",
    "sqlalchemy>=2.0.43",
    "sqlmodel>=0.0.25",
]
